### ISSUE TITLE
If the device is landscape when app start, all value is opposite.

### ISSUE THREAD

**Issue by swainet** [kkjdaniel/react-native-device-display#11]
All value is opposite when device is landscape when app start.

**Comment by kkjdaniel** [comment]
I will look into this, thanks!

**Comment by jforaker** [comment]
+1

**Comment by jforaker** [comment]
Possibly only an issue in the Simulator?  Not exactly sure tho, as it seems very brittle. Should be investigated imo

**Comment by JoaoCnh** [comment]
This is a big issue. I'm also getting a problem where even if my app starts as Portraint and I rotate the device to Landscape it still says Portrait. And after that the toggle works but in reverse. Landscape when it should be Portrait and vice versa.

**Comment by DaleLJefferson** [comment]
This issue has been fixed in the master but has not been released to npm yet. I had the same issue but now it's working fine.

```
"react-native-device-display": "kkjdaniel/react-native-device-display",
```

@kkjdaniel Can you release 1.0.5 with this fix.

Issue was fixed in this commit

> fix reversed width/height https://github.com/kkjdaniel/react-native-device-display/commit/7fe4a47cddf6e05e01becb49ffbcecf7fab33896

**Comment by kkjdaniel** [comment]
Sorry for the wait guys I am releasing the fixes for this today! - Thanks
