### ISSUE TITLE
Seems to be incompatible with React Native 0.14.x and 0.13.x

### ISSUE THREAD

**Issue by natorojr** [kkjdaniel/react-native-device-display#15]
I recently upgraded my app to React Native 0.14.x and react-native-device-display is causing the following errors to show up in the console:

2015-11-16 23:40:17.179 [error][tid:main][RCTBatchedBridge.m:436] Error while loading: Unable to resolve module Dimensions from /Users/XXX/XXX/XXX/node_modules/react-native-device-display/display.js: Invalid directory /Users/node_modules/Dimensions

<img width="487" alt="screen shot 2015-11-16 at 11 40 25 pm" src="https://cloud.githubusercontent.com/assets/1237186/11205718/bad79d0c-8cbe-11e5-9553-8eb8276996b0.png">

**Comment by natorojr** [comment]
Actually, looks like I'm seeing the same errors with 0.13.x, but it doesn't show up in the Xcode console, it only shows up in the dev server window.

Unable to resolve module Dimensions from /Users/XXX/XXX/XXX/node_modules/react-native-device-display/display.js
Unable to resolve module RCTDeviceEventEmitter from /Users/XXX/XXX/XXX/node_modules/react-native-device-display/display.js

**Comment by natorojr** [comment]
Changing title based on findings from last comment

**Comment by natorojr** [comment]
Submitted a PR #16 which seems to fix the issue

**Comment by natorojr** [comment]
@kkjdaniel Just wondering if this project still active? I don't mind waiting (since I know we're all busy), but just want to know so I can start transitioning my projects to a different solution if this is going away. -Best

**Comment by natorojr** [comment]
We moved to a different technique (using Dimension directly). This is not a priority for us anymore.

Will leave open in case others encounter.

**Comment by gajuro** [comment]
@natorojr thanks for the PR. 
Do you suggest that we can detect orientation by using Dimensions directly? Mean while we will use your fork of this repo.
