### ISSUE TITLE
Submitting a pull request

### ISSUE THREAD

**Issue by albertwchang** [kkjdaniel/react-native-device-display#17]
Forgive me if this question is stupid, but I am wondering how I can update my forked version to the current version of this repo.  My fork is currently @1.0.0, and I want to create a pull request from my base , and submit it to kkdaniel's master branch.

Please advise.  Thanks.  -Albert

**Comment by kkjdaniel** [comment]
Is this still an issue? To update your fork make a pull request from the Master branch.

Thanks,
Karl
