### ISSUE TITLE
UI Error Message after upgrading to React Native 0.7.1

### ISSUE THREAD

**Issue by albertwchang** [kkjdaniel/react-native-device-display#2]
Hello.  I get the following error message after installing this module, and trying to run the default app that is created from latest react-native version (0.7.1), e.g. `react-native init Test`.  I responded to someone'e else inquiry about error messages occurring after upgrading to React Native 0.7.1:  https://github.com/facebook/react-native/issues/1960

![react-native error](https://cloud.githubusercontent.com/assets/3760499/8641338/321f8998-28c8-11e5-9594-facd04a653c0.png)

**Comment by kkjdaniel** [comment]
I'll take a look into this!

**Comment by albertwchang** [comment]
So I followed the advice of the last post from @mikesurowiec (https://github.com/facebook/react-native/issues/1960), and his advice was a suitable fix for the time being.  Just tried your library out.  Good stuff!  Thanks!

**Comment by kkjdaniel** [comment]
Thanks for this, looks like I will need to fiddle around with the NPM package, I'll push out a fix for this shortly.
