### ISSUE TITLE
Is orientation worked for a build product-apk

### ISSUE THREAD

**Issue by SamTharani** [kkjdaniel/react-native-device-display#20]
Hi all
I tried the same thing for a react-native android application. Its took the value of the screen width, height using Dimension when I reload the js otherwise this orientation (width, height changing) not worked. Can you help me to fix this issue

Thank you

**Comment by kkjdaniel** [comment]
I will be adding Android support over the coming month - https://github.com/kkjdaniel/react-native-device-display/issues/10
