### ISSUE TITLE
NPM Updates on Dimensions import issue

### ISSUE THREAD

**Issue by ghost** [kkjdaniel/react-native-device-display#21]
Hi, when i do npm install on react-native-device-display, i still get the old codes:

var { NativeModules } = require('react-native');

var DeviceUtil = NativeModules.DisplayDeviceUtil;
var Dimensions = require('Dimensions');
var RCTDeviceEventEmitter = require('RCTDeviceEventEmitter');

Which displays the Module not found error. But i can see that this is fixed on Github copy but i'm not getting the update whenever i npm install.

FIX Code:

---

var {
  Dimensions,
  RCTDeviceEventEmitter,
  NativeModules
} = require('react-native');

var DeviceUtil = NativeModules.DisplayDeviceUtil;

Thanks.

**Comment by kkjdaniel** [comment]
The NPM version will be updated in the upcoming release.
