### ISSUE TITLE
Missing tag for master

### ISSUE THREAD

**Issue by el-lsan** [kkjdaniel/react-native-device-display#24]
currently the tag for the master is missing and if you follow the documentation and run 

`npm install react-native-device-display` 

You will get a different version from the latest release.

P.S: temporary solution for those who are facing this issue: 
Use following in your package.json 
`"react-native-device-display": "kkjdaniel/react-native-device-display#master",`

**Comment by kkjdaniel** [comment]
This will be updated to fix the NPM version in the next release.
