### ISSUE TITLE
Unlisten to Display.onOrientationDidChange

### ISSUE THREAD

**Issue by albertwchang** [kkjdaniel/react-native-device-display#4]
Does this method get unregistered after the underlying component gets unmounted?  If not, i'm wondering how one can do so (unregister this listener).

**Comment by kkjdaniel** [comment]
Will be adding this feature in shortly - expect it within the next couple of days.

**Comment by albertwchang** [comment]
@kkjdaniel:  I just tried `npm install react-native-device-display@latest` roughly 3 times, and never did the downloads reflect the latest update (e.g. returning the subscriber from RCTEventEmitter.addListener()).  Just an fyi...

**Comment by kkjdaniel** [comment]
Sorry, I have only now pushed the latest package to NPM.

**Comment by albertwchang** [comment]
no problemo.  Sweet!  thanks for the update.
