### ISSUE TITLE
Support newest versions of React Native

### ISSUE THREAD

**Issue by joeyvandijk** [kkjdaniel/react-native-device-display#6]
I've seen your last commit, but while using React Native 0.7.1 & 0..8.0.rc.2 are giving me errors installing your module. Could you alter your peerDepedencies less strict, while now I cannot use (without hassle) your module in the new updates of React Native. Could you update like `react-native-icons` has done for example:

``` json
"peerdependencies" : {
    "react-native": ">=0.6.0 <1.0.0"
}
```

Thanks!

**Comment by kkjdaniel** [comment]
~~I'll push out an update today, thanks!~~ All done!

**Comment by joeyvandijk** [comment]
Thanks, but I found out that the `0.x.x.-rc.x` releases where not compatible, so could you update it to 

``` json
"peerdependencies" : {
    "react-native": ">=0.6.0-rc || >=0.7.0-rc || >=0.8.0-rc || >=0.9.0-rc"
}
```

check if you want at [NPM Semver](http://semver.npmjs.com) to see which releases are tackled (use react-native).

Thanks again for your quick response!

**Comment by kkjdaniel** [comment]
Good spot, all fixed now and published to NPM, thanks!

**Comment by joeyvandijk** [comment]
Great!! ;)
