### ISSUE TITLE
GPL - Incompatible with iOS App Store

### ISSUE THREAD

**Issue by DaleLJefferson** [kkjdaniel/react-native-device-display#7]
The GPL is incompatible with the iOS App Store and proprietary software development. I'm not sure how many people are looking to build a GPL app and not distribute it on the App Store. 

I would hazard to guess that the 500 users who have downloaded this library, the majority of them will be breaking the terms of your licence and putting themselves at risk of legal action.

I would suggest a less restrictive license like MIT, Apache or BSD.

**Comment by kkjdaniel** [comment]
I'll be perfectly honest I've always defaulted to GPL, though it's a good point especially considering most will be looking to release there apps. I'll bring the project inline with the standard React Native library using the BSD license - Thanks!
